name: sistema
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter   
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  provider: ^6.1.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.0.7
  geolocator: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/baches.db
    